application: twearchy
version: 1
runtime: python
api_version: 1

handlers:

- url: /img
  static_dir: img

- url: /css
  static_dir: css

- url: /.*
  script: twearchy.py

builtins:
- datastore_admin: on
